"""master_data_v2

Revision ID: xxxxxxxx
Revises: yyyyyyyy
Create Date: 2023-10-28 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'xxxxxxxx'
down_revision: Union[str, None] = 'yyyyyyyy' # Previous migration ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('departments', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('departments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('departments', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('departments', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'departments', 'users', ['updated_by_id'], ['id'])

    # ... Other tables (sections, fuel_types, vehicles) are modified similarly ...

    op.create_table('department_fuel_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('fuel_type_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'fuel_type_id', name='uq_department_fuel_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_fuel_matrix')

    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'updated_by_id')
    op.drop_column('departments', 'created_by_id')
    op.drop_column('departments', 'deleted_at')
    op.drop_column('departments', 'company_id')

    # ... Downgrade for other tables ...

    op.drop_table('companies')
    # ### end Alembic commands ###