"""add_permission_matrix

Revision ID: 4fdd25f7780e
Revises: 2761f522cabc
Create Date: 2026-09-10 11:01:30.917233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdd25f7780e'
down_revision: Union[str, None] = '2761f522cabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'module', 'permission', name='uq_permission_matrix')
    )
    op.add_column('profiles', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'company_id')
    op.drop_table('permission_matrix')
    # ### end Alembic commands ###
